# Researchable
MVP_PATH="/Users/mario/Developer/Researchable/MVP/base-platform"
alias mvp="cd ${MVP_PATH}"
alias drails="${MVP_PATH}/bin/be rails"
alias dbundle="${MVP_PATH}/bin/bundle"
alias dbe="${MVP_PATH}/bin/be"
alias rspec="dbe rspec"
alias jest="dbe yarn run jest"
alias rubocop="dbe rubocop -a"
alias standardjs="${MVP_PATH}/bin/standard"
alias nuke="drails db:drop && drails db:create && drails db:migrate && drails db:seed"
