"" Source vimrc automatically
autocmd! bufwritepost ~/.vim/vimrc source %

" easier moving between tabs
map <Leader>n <esc>:tabprevious<CR>
map <Leader>m <esc>:tabnext<CR>
map <Leader>t <esc>:tabnew<CR>

" map sort function to a key
vnoremap <Leader>s :sort<CR>

" Show whitespace
" MUST be inserted BEFORE the colorscheme command
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
au InsertLeave * match ExtraWhitespace /\s\+$/

" Split to the right and bottom
set splitright
set splitbelow

" Line number at cursor line and relative numbering for the rest of the lines
set number
set relativenumber

"change default indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab

" Better indentation edition
vnoremap < <gv
vnoremap > >gv

" Improved search
set hlsearch " Keep search highlight once done with search
set incsearch " Highlight as you type search
set ignorecase " Ignore case if search string is lowercase
set smartcase " Don't ignore case if search string has uppercase
nnoremap <esc><esc> :noh<return> " Press esc twice to disable highlight

" disable folding
set nofoldenable

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'christoomey/vim-tmux-navigator' " C-{h,j,k,l} hotkeys for tmux and vim navigation
Plug 'blueshirts/darcula' " Jetbrains like colorscheme
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'sheerun/vim-polyglot' " filetype language packs (syntax and indent)
Plug 'kien/ctrlp.vim' " Fuzzy search
"Plug 'davidhalter/jedi-vim', {'tag': '0.9.0'} " Python ide
"Plug 'hdima/python-syntax' " Highlight self in python classes
"Plug 'nvie/vim-flake8' " Pep8 checks

call plug#end()

colorscheme darcula
